spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    sql:
        init:
            platform: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        show-sql: true